Diploma/urls.py
from django.contrib import admin
from django.urls import include, path, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ripc.urls')),
]

ripc/urls.py
from django.urls import path, include
from django.contrib.auth import views as authViews

from . import views
from .logic.complect import complect
from .logic.mark import mark
from .logic.criteria import criteria
from .logic.criteria_cropping import criteria_cropping
from .logic.event_organization import event_organization
from .logic.pattern_task import pattern_task
from .logic.region import region
from .logic.organization import organization
from .logic.expert import expert
from .logic.event import event
from .logic.scanned_page import scanned_page
from .logic.scanner import scanner
from .logic.subject import subject
from .logic.task import task
from .logic.variant import variant
from .logic.variant_cropping import variant_cropping
# Роутер-массив с путями и вызываемыми функциями по запросу
urlpatterns = [
    path('logout/', authViews.LogoutView.as_view(next_page='/accounts/login/'), name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('create_event/', views.create_event, name='create_event'),

    # Административная панель
    path('experts/', expert.experts, name='experts'),
    path('experts/<int:expert_id>', expert.experts_detail, name='experts_detail'),
    path('experts/reg/', expert.experts_reg, name='experts_reg'),
    path('regions/', region.regions, name='regions'),
    path('regions/edit/<int:reg_id>', region.regions_edit, name='regions_edit'),
    path('regions/<int:reg_id>', region.regions_detail, name='regions_detail'),
    path('regions/reg', region.regions_reg, name='regions_reg'),
    path('organizations/', organization.organizations, name='orgs'),
    path('organizations/reg/', organization.organizations_registration, name='org_reg'),
    path('organizations/edit/<int:org_id>', organization.organizations_edit, name='orgs_edit'),
    path('organizations/<int:org_id>', organization.organizations_detail, name='orgs_detail'),

    # API
    path('api/subject/', subject.subject_api, name='subject_api'),
    path('api/event/', event.event_api, name='event_api'),
    path('api/event/<int:id>', event.event_api, name='event_api'),
    path('api/variant/', variant.variant_api, name='variant_api_post'),
    path('api/variant/file/<int:id>', variant.variant_api_file, name='variant_api_file'),
    path('api/cropping_variant/start/<int:id>', variant_cropping.start_cropping_variant, name='start_cropping_variant'),
    path('api/cropping_variant/image/<int:id>', variant_cropping.cropping_variant_image, name='cropping_variant_image'),
    path('api/pattern_task/', pattern_task.pattern_api, name='pattern_api'),
    path('api/task/', task.task_api, name='task_api'),
    path('api/organization/', organization.organizations_api, name='organizations_api'),
    path('api/event_organization/', event_organization.event_organizations_api, name='event_organizations_api'),
    path('api/complect_scan/', scanned_page.complect_scan_data, name='complect_scan_data'),
    path('api/scanned_page/file/<int:id>', scanned_page.scanned_api_file, name='scanned_api_file'),
    path('api/scanned_page/files/<int:id>', scanned_page.scanned_api_files, name='scanned_api_files'),
    path('api/scanned_page/<int:id>', scanned_page.scanned_api, name='scanned_api'),
    path('api/scanned_page/scan', scanned_page.file_from_scanner, name='file_from_scanner'),
    path('api/complects/generate', complect.complects_generate, name='complects_generate'),
    path('api/criteria/', criteria.criteria_api, name='criteria_api'),
    path('api/criteria/file/<int:id>', criteria.criteria_api_file, name='criteria_api_file'),
    path('api/cropping_criteria/start/<int:id>', criteria_cropping.start_cropping_criteria,
         name='start_cropping_criteria'),
    path('api/cropping_criteria/image/<int:id>', criteria_cropping.cropping_criteria_image,
         name='cropping_criteria_image'),

    # Страницы
    path('', views.index, name='index'),
    path('create_event', event.create_event, name='create_event'),
    path('edit_event/<int:event_id>/', event.edit_event, name='edit_event'),
    path('event/<int:event_id>/', event.view_event, name='view_event'),
    path('event_organization/<int:event_id>', event_organization.view_event_organization,
         name='view_event_organization'),
    path('events', event.view_events, name='view_events'),
    path('marking/<int:event_id>/', mark.marking, name='marking'),

    # Скачивание Scanner
    path('scanner/download/', scanner.scanner_download, name='scanner_download'),

    # Скачивание комплектов
    path('complects/download/<int:event_id>', complect.complects_download, name='complects_download'),

]

ripc/models.py
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator, MinLengthValidator
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User


# Файл с моделями - таблицами в базе данных
# Модель предметных областей
class Subject(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


# Модель региона
class Region(models.Model):
    name = models.CharField(max_length=300)

    def __str__(self):
        return self.name

    @classmethod
    def create(cls, name):
        region = cls(name=name)
        region.save()
        return region


# Модель организации
class Organization(models.Model):
    name = models.CharField(max_length=300)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    @classmethod
    def create(cls, name, region):
        org = cls(name=name, region=region)
        org.save()
        return org


# Модель статусов экспертов
class ExpertStatus(models.Model):
    status = models.CharField(max_length=50, default='Работает')


# Модель эксперта
class Expert(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    surname = models.CharField(max_length=30)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    referee = models.BooleanField()
    status = models.ForeignKey(ExpertStatus, on_delete=models.CASCADE)
    delta = models.IntegerField()

    @classmethod
    def create(cls, data):
        user = User.objects.create_user(data['username'], data['email'], data['password'])
        user.last_name = data['last_name']
        user.first_name = data['first_name']
        user.save()

        org = Organization.objects.get(pk=data['organization'])
        subject = Subject.objects.get(pk=data['subject'])

        expert = cls(surname=data['surname'], user=user, referee=data['referee'], org=org, subject=subject)
        expert.save()
        return expert


# Модель администратора
class Admin(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    surname = models.CharField(max_length=30)


# Модель представителя региона
class RegionRep(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    surname = models.CharField(max_length=30)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)


# Модель представителя организации
class OrganizationRep(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    surname = models.CharField(max_length=30)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)


# Модель мероприятия
class Event(models.Model):
    name = models.CharField(max_length=300)
    start_date = models.DateField()
    end_date = models.DateField()
    region = models.ForeignKey(Region, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


# Модель варианта
class Variant(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    page_count = models.CharField(max_length=2)
    file_path = models.TextField(null=True)


# Модель вырезки варианта
class VariantCropping(models.Model):
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE)
    task_num = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    answer_coord = ArrayField(models.IntegerField())


# Модель шаблона задания
class PatternTask(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    task_num = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    max_score = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    check_times = models.IntegerField()


# Модель критерий
class Criteria(models.Model):
    variant = models.OneToOneField(Variant, on_delete=models.CASCADE)
    file_path = models.TextField(null=True)


# Модель вырезки критериев
class CriteriaCropping(models.Model):
    criteria = models.ForeignKey(Criteria, on_delete=models.CASCADE)
    task_num = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    file_path = models.TextField(null=True)


# Модель задания
class Task(models.Model):
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE)
    pattern = models.ForeignKey(PatternTask, on_delete=models.CASCADE)
    variant_cropping = models.ForeignKey(VariantCropping, on_delete=models.CASCADE)
    criteria_cropping = models.ForeignKey(CriteriaCropping, on_delete=models.CASCADE)
    task_num = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])


# Смежная модель задания-эксперта
class TaskExpert(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    expert = models.ForeignKey(Expert, on_delete=models.CASCADE)
    check_date = models.DateTimeField()
    check_time = models.IntegerField()


# Модель статуса мероприятия
class EventStatus(models.Model):
    name = models.CharField(max_length=20)
    color_hex = models.CharField(validators=[MinLengthValidator(6)], max_length=7)


# Расширенная модель мероприятия на организацию
class OrganizationEvent(models.Model):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    event_status = models.ForeignKey(EventStatus, on_delete=models.CASCADE)
    percent_status = models.TextField(max_length=4, null=True)
    number_participants = models.TextField(max_length=5, null=True)


# Смежная модель мероприятия-эксперта
class EventExperts(models.Model):
    expert = models.ForeignKey(Expert, on_delete=models.CASCADE)
    event = models.ForeignKey(OrganizationEvent, on_delete=models.CASCADE)


# Модель комплекта
class Complect(models.Model):
    organization_event = models.ForeignKey(OrganizationEvent, on_delete=models.CASCADE)
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE)
    is_additional = models.BooleanField(default=False)
    file_path = models.TextField(null=True)


# Модель ответа студента
class Answer(models.Model):
    complect = models.ForeignKey(Complect, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    file_path = models.TextField(null=True)
    mark = models.CharField(max_length=10, null=True)


# Модель 3 оценки ответа
class ThirdMark(models.Model):
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    check_date = models.DateTimeField()
    check_time = models.IntegerField()


# Смежная таблица 3 оценки-эксперта
class ThirdMarkExpert(models.Model):
    third_mark = models.ForeignKey(ThirdMark, on_delete=models.CASCADE)
    expert = models.ForeignKey(Expert, on_delete=models.CASCADE)


# Модель отсканированных страниц
class ScannedPage(models.Model):
    organization_event = models.ForeignKey(OrganizationEvent, on_delete=models.CASCADE)
    complect = models.ForeignKey(Complect, on_delete=models.CASCADE, null=True)
    page_number = models.CharField(max_length=2, null=True)
    file_path = models.TextField(null=True)


# Модель уведомления
class Notification(models.Model):
    date = models.DateField()
    event_expert = models.ForeignKey(EventExperts, on_delete=models.CASCADE)
    message = models.CharField(max_length=300)

    @classmethod
    def create(cls, date, event_expert, message):
        notification = cls(date=date, event_expert=event_expert, message=message)
        notification.save()
        return notification

ripc/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

from ripc.models import Expert


class RegisterUserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email']
        fields_expert = ['region', 'org', 'subject', 'third_check']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

ripc/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import DeleteView, DetailView, CreateView
from django.urls import reverse_lazy
from .models import *
from .forms import RegisterUserForm

# Функция отображения главной страницы
@login_required(login_url='/accounts/login/')
def index(request):
    context = {'user': request.user}
    return render(request, 'index.html', context)


@login_required(login_url='/accounts/login/')
def detail(request, question_id):
    expert_name = get_object_or_404(Expert, pk=question_id)
    return render(request, '', {'name': expert_name})


@login_required(login_url='/accounts/login/')
def create_event(request):
    context = {}
    return render(request, 'main_pages/create_event.html', context)


@login_required(login_url='/accounts/login/')
def view_event(request, event_id):
    context = {}
    return render(request, 'main_pages/view_event.html', context)


@login_required(login_url='/accounts/login')
def events_resp(request):
    contex = {}
    return render(request, 'main_pages/events_resp.html', contex)


# Функция авторизации пользователя
@login_required(login_url='/accounts/login/')
class RegisterUserView(CreateView):
    form_class = RegisterUserForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form_valid = super().form_valid(form)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        auth_user = authenticate(username=username, password=password)
        login(self.request, auth_user)
        return form_valid

    def get_success_url(self):
        return self.success_url

ripc/templates/structure/experts/expert_list.html
{% extends "base_menu_generic.html" %}
{% load static %}
{% block title %}Эксперты{% endblock %}

{% block main_content %}
    <div class="container mt-3 pb-1">
        <h3 class="display-6 my-4 fw-normal">Эксперты</h3>
        <div class="row align-items-start table-naming">
            <div class="col-1">№</div>
            <div class="col-3">ФИО</div>
            <div class="col-2">Статус</div>
            <div class="col-2">Предмет</div>
            <div class="col-2">Организация</div>
            <div class="col-2">Мероприятия</div>
        </div>
        {% if experts.count > 0 %}
            <div class="rounded-3">
                {% for expert in experts %}
                    <div class="row align-items-start bg-light py-2">
                        <div class="col-1">{{ expert.id }}</div>
                        <div class="col-3">
                            {{ expert.user.first_name }} {{ expert.user.last_name }} {{ expert.surname }}</div>
                        <div class="col-2">{{ expert.status.status }}</div>
                        <div class="col-2">{{ expert.subject.name }}</div>
                        <div class="col-2"><a href="/organizations/{{ expert.organization.id }}">{{ expert.organization.name }}</a></div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p class="mt-2">Нет доступных экспертов</p>
        {% endif %}
        <div class="flex-row d-flex justify-content-end w-90">
            <a href="/experts/reg/">
                <button class="btn btn-primary rounded-pill px-3 my-4" type="button">Добавить эксперта</button>
            </a>
        </div>
    </div>
{% endblock %}

ripc/templates/structure/experts/expert_reg.html
{% extends "base_menu_generic.html" %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Регистрация Эксперта{% endblock %}

{% block main_content %}
    <div class="w-50 expert-reg container mt-3 pb-1 rounded-2 border px-5 pb-4 border-opacity-50 border-1 border-dark">
        <h3 class="display-6 my-4 fw-normal">Регистрация эксперта</h3>
        <main class="w-100 m-auto">
            <form action="{% url 'experts_reg' %}" method="post" class="need-validation" novalidate>
                {% csrf_token %}

                <div class="row g-3">
                    <div class="col-sm-6">
                        {{ user_form.first_name | as_crispy_field }}

                    </div>

                    <div class="col-sm-6">
                        {{ user_form.last_name | as_crispy_field }}
                        {{ user_form.last_name.errors }}


                    </div>

                    <div class="col-12">
                        <label for="{{ user_form.last_name.id_for_label }}" class="form-label">Отчество</label>
                        {{ expert_form.surname | as_crispy_field }}
                        {{ expert_form.surname.errors }}


                    </div>

                    <div class="col-12">
                        {{ user_form.username | as_crispy_field }}
                        {{ user_form.username.errors }}
                    </div>

                    <div class="col-12">
                        {{ user_form.password | as_crispy_field }}
                        {{ user_form.password.errors }}

                    </div>

                    <div class="col-12">
                        {{ user_form.email | as_crispy_field }}
                        {{ user_form.email.errors }}

                    </div>

                    <div class="col-12">
                        <label for="{{ expert_form.organization.id_for_label }}" class="form-label">Организация</label>
                        {{ expert_form.organization | as_crispy_field }}
                        {{ expert_form.organization.errors }}

                    </div>

                    <div class="col-md-6">
                        <label for="{{ expert_form.subject.id_for_label }}" class="form-label">Предмет</label>
                        {{ expert_form.subject | as_crispy_field }}
                        {{ expert_form.subject.errors }}
                    </div>

                    <div class="col-md-6">
                        <label for="{{ expert_form.referee.id_for_label }}" class="form-label">Право третьей
                            проверки</label>
                        {{ expert_form.referee | as_crispy_field }}
                        {{ expert_form.referee.errors }}
                    </div>

                    <button type="submit" class="btn mt-5 btn-primary">Сохранить</button>
                </div>
            </form>
        </main>
    </div>
    <script>
        var select_box_element = document.querySelector('#id_organization');
        dselect(select_box_element, {
            search: true
        });
    </script>
{% endblock %}